### ISSUE TITLE
Zadanie uzupełniające

### ISSUE THREAD

**Issue by kamrar** [mwanielista/zadanie-api#1]
Dorób mi prosze do obu apek Dockerfila tak żebym mógł sobie wszystko zbudować i odpalić na dockerze. + instrukcja

**Comment by mwanielista** [comment]
Witam,
dorobiłem Dockerfile do obydwóch serwisów oraz, w głównym katalogu, docker-compose. 

Instrukcję instalacji dodałem na końcu readme.
