### ISSUE TITLE
secondQuery

### ISSUE THREAD

**Issue by kamrar** [mwanielista/zadanie-api#2]
https://github.com/mwanielista/zadanie-api/blob/b16457a83a6e6f10e211bd47172988b658f76894/Zad2/src/main/java/eu/wanielista/zad2/repository/DbRepository.java#L30

W secondQuery chodziło o stworzenie endpointa ktory w zapytaniu przyjmuje listę pól jakie użytkownik chce pobrać.
czyli generateCSV przyjmuje np w parametrze "id, latitude, longitude" i w takim formacie jest generowany csv ale jak user poda 'country,fullName' no to juz mamy co innego :)

**Comment by kamrar** [comment]
a i zrob mi prosze ze zmian PRa

**Comment by mwanielista** [comment]
Przepraszam, niestety źle zrozumiałem polecenie. 
Teraz już działa poprawnie, wszystkie zmiany zawarłem w PR.
